name: testing-workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Which env moved"
        default: "dev"
        type: choice
        options:
        - dev
        - prod
      

jobs:
  prod:
    if: ${{ github.event_name == 'push' && github.ref_name == 'testing' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_REACT_APP_REGION: ${{ secrets.REACT_APP_REGION }}
          envkey_REACT_APP_LIVE_API_URL: ${{ secrets.REACT_APP_LIVE_API_URL }}
          envkey_REACT_APP_BUCKETNAME: ${{ secrets.REACT_APP_BUCKETNAME }}
          envkey_REACT_APP_CLIENT_LIVE_URL: ${{ secrets.REACT_APP_CLIENT_LIVE_URL }}
          envkey_REACT_APP_ADMIN_LIVE_URL: ${{ secrets.REACT_APP_ADMIN_LIVE_URL }}
          envkey_REACT_APP_SECRETACCESSKEY: ${{ secrets.REACT_APP_SECRETACCESSKEY }}
          envkey_REACT_APP_ACCESSKEY_ID: ${{ secrets.REACT_APP_ACCESSKEY_ID }}
          envkey_REACT_APP_RECAPTCHA: ${{ secrets.REACT_APP_RECAPTCHA }}
          
          directory: './'
          file_name: .env
          fail_on_empty: false  
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i --legacy-peer-deps
      - run: "CI=false npm run build:production"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.REACT_APP_ACCESSKEY_ID }}
          aws-secret-access-key: ${{ secrets.REACT_APP_SECRETACCESSKEY }}
          aws-region: us-east-1
      - run: aws s3 sync ./build s3://stag-client.castingbell.com
  
  
